package onlineshop;
import onlineshop.ShoppingCart;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.util.List;
import java.time.LocalDateTime;
import java.util.ArrayList;
import onlineshop.Order;
import onlineshop.ShoppingCart.CartItem;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author TIARA
 */
public class FormCheckout extends javax.swing.JFrame {

    /**
     * Creates new form FormCheckout
     */
    private ShoppingCart cart;
    private int totalHarga;
    
    

    public FormCheckout(ShoppingCart cart, int totalHarga) {
        initComponents();
        this.cart = cart;
        this.totalHarga = totalHarga;
        


        double total = 0;
        for (ShoppingCart.CartItem item : cart.getItems()) {
            total += item.getProduct().calculateFinalPrice() * item.getQuantity();
        }



        txtTotalHarga.setText(String.valueOf(totalHarga));
        txtTotalHarga.setEditable(false);
        txtKembalian.setEditable(false);
        
        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hitungKembalian();
            }
        });

    }
    
    private void hitungKembalian() {
        try {
            int bayar = Integer.parseInt(txtBayar.getText());
            int kembalian = bayar - totalHarga;

            if (kembalian < 0) {
                txtKembalian.setText("Pembayaran kurang");
            } else {
                txtKembalian.setText("Rp " + kembalian);
            }
        } catch (NumberFormatException e) {
            txtKembalian.setText("Masukkan angka");
        }
    }
    
        

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new javax.swing.JPanel();
        header1 = new javax.swing.JPanel();
        titleBeranda = new javax.swing.JLabel();
        bgpanelPilihan = new javax.swing.JPanel();
        bglabelPilihan = new javax.swing.JLabel();
        bglabelPilihan1 = new javax.swing.JLabel();
        bglabelPilihan2 = new javax.swing.JLabel();
        bglabelPilihan3 = new javax.swing.JLabel();
        bglabelPilihan4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNama = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTotalHarga = new javax.swing.JTextArea();
        txtBayar = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        footer1 = new javax.swing.JPanel();
        btnKembali = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background1.setBackground(new java.awt.Color(238, 223, 200));

        header1.setBackground(new java.awt.Color(220, 198, 166));

        titleBeranda.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        titleBeranda.setForeground(new java.awt.Color(249, 238, 223));
        titleBeranda.setText("CHECKOUT");

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleBeranda)
                .addContainerGap(602, Short.MAX_VALUE))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(titleBeranda)
                .addContainerGap())
        );

        bgpanelPilihan.setBackground(new java.awt.Color(219, 197, 166));

        bglabelPilihan.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bglabelPilihan.setForeground(new java.awt.Color(102, 0, 0));
        bglabelPilihan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bglabelPilihan.setText("ALAMAT");

        bglabelPilihan1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bglabelPilihan1.setForeground(new java.awt.Color(102, 0, 0));
        bglabelPilihan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bglabelPilihan1.setText("NAMA PEMESAN");

        bglabelPilihan2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bglabelPilihan2.setForeground(new java.awt.Color(102, 0, 0));
        bglabelPilihan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bglabelPilihan2.setText("NOMINAL PEMBAYARAN");

        bglabelPilihan3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bglabelPilihan3.setForeground(new java.awt.Color(102, 0, 0));
        bglabelPilihan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bglabelPilihan3.setText("KEMBALIAN");

        bglabelPilihan4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bglabelPilihan4.setForeground(new java.awt.Color(102, 0, 0));
        bglabelPilihan4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bglabelPilihan4.setText("TOTAL HARGA");

        txtNama.setBackground(new java.awt.Color(252, 244, 234));
        txtNama.setColumns(20);
        txtNama.setRows(5);
        jScrollPane1.setViewportView(txtNama);

        txtAlamat.setBackground(new java.awt.Color(252, 244, 234));
        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        txtTotalHarga.setBackground(new java.awt.Color(252, 244, 234));
        txtTotalHarga.setColumns(20);
        txtTotalHarga.setRows(5);
        jScrollPane4.setViewportView(txtTotalHarga);

        txtBayar.setBackground(new java.awt.Color(252, 244, 234));

        txtKembalian.setBackground(new java.awt.Color(252, 244, 234));
        txtKembalian.setForeground(new java.awt.Color(102, 51, 0));

        javax.swing.GroupLayout bgpanelPilihanLayout = new javax.swing.GroupLayout(bgpanelPilihan);
        bgpanelPilihan.setLayout(bgpanelPilihanLayout);
        bgpanelPilihanLayout.setHorizontalGroup(
            bgpanelPilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelPilihanLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(bgpanelPilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bglabelPilihan4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bglabelPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bglabelPilihan1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bglabelPilihan3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bglabelPilihan2))
                .addGap(33, 33, 33)
                .addGroup(bgpanelPilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(txtBayar)
                    .addComponent(txtKembalian))
                .addGap(0, 65, Short.MAX_VALUE))
        );
        bgpanelPilihanLayout.setVerticalGroup(
            bgpanelPilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgpanelPilihanLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(bgpanelPilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgpanelPilihanLayout.createSequentialGroup()
                        .addComponent(bglabelPilihan1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgpanelPilihanLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(bgpanelPilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bglabelPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgpanelPilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgpanelPilihanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(bglabelPilihan4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                    .addGroup(bgpanelPilihanLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgpanelPilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bglabelPilihan2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(bgpanelPilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bglabelPilihan3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        footer1.setBackground(new java.awt.Color(220, 198, 166));

        btnKembali.setBackground(new java.awt.Color(252, 244, 234));
        btnKembali.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(102, 51, 0));
        btnKembali.setText("BACK");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnBayar.setBackground(new java.awt.Color(252, 244, 234));
        btnBayar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnBayar.setForeground(new java.awt.Color(102, 51, 0));
        btnBayar.setText("BAYAR");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footer1Layout = new javax.swing.GroupLayout(footer1);
        footer1.setLayout(footer1Layout);
        footer1Layout.setHorizontalGroup(
            footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footer1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(30, 30, 30))
        );
        footer1Layout.setVerticalGroup(
            footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footer1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bgpanelPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bgpanelPilihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(footer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new FormKeranjang(this.cart).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText().trim();
        String alamat = txtAlamat.getText().trim();
        String bayarStr = txtBayar.getText().trim();

        if (nama.isEmpty() || alamat.isEmpty() || bayarStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi semua data!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
           double bayar = 0;
           double kembalian = 0;
        try {
            bayar = Double.parseDouble(bayarStr);
            if (bayar < totalHarga) {
                JOptionPane.showMessageDialog(this, "Uang tidak cukup!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            kembalian = bayar - totalHarga;
            txtKembalian.setText(String.valueOf(kembalian));

            JOptionPane.showMessageDialog(this, "Pembayaran berhasil!\nTerima kasih, " + nama, "Sukses", JOptionPane.INFORMATION_MESSAGE);

            new FormBeranda(cart).setVisible(true);
            this.dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan nominal uang yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        Order order = new Order(nama, alamat, totalHarga, bayar, kembalian, new ArrayList<>(cart.getItems()));
        cart.addOrder(order);
        cart.clear();  // Kosongkan keranjang setelah bayar


    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background1;
    private javax.swing.JLabel bglabelPilihan;
    private javax.swing.JLabel bglabelPilihan1;
    private javax.swing.JLabel bglabelPilihan2;
    private javax.swing.JLabel bglabelPilihan3;
    private javax.swing.JLabel bglabelPilihan4;
    private javax.swing.JPanel bgpanelPilihan;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JPanel footer1;
    private javax.swing.JPanel header1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel titleBeranda;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextArea txtNama;
    private javax.swing.JTextArea txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
