import onlineshop.ProductNotFoundException;
import onlineshop.Product;
import onlineshop.ProductManager;
import onlineshop.Size;
import onlineshop.Electronics;
import onlineshop.Clothing;
import onlineshop.ShoppingCart;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.awt.Color;
import javax.swing.*;
import java.util.List; 




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author TIARA
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    DefaultTableModel model;
    private ShoppingCart cart;
    private ProductManager productManager;

    
    public FormMenu(ShoppingCart cart) {
        initComponents();
        btnTambah = new javax.swing.JButton();
        btnTambah.setText("Keranjang");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeranjangActionPerformed(evt);
            }
        });

        model = (DefaultTableModel) tableProduk.getModel();

        this.cart = cart;
        this.productManager = new ProductManager();
        productManager.addProduct(new Electronics(1, "Laptop ASUS", 9000000, 1.5, "Asus", "Brand: ASUS, Berat: 1,5 kg"));
        productManager.addProduct(new Electronics(2, "HP Samsung", 6000000, 0.2, "Samsung", "Brand: Samsung, Berat: 0,2 kg"));
        productManager.addProduct(new Electronics(3, "TV LG", 1500000, 2.0, "LG", "Brand: LG, Berat: 7 kg"));
        productManager.addProduct(new Electronics(4, "Kipas Angin", 250000, 2.0, "Maspion", "Brand: Maspion, Berat: 2 kg"));
        productManager.addProduct(new Clothing(5, "Baju Polos", 120000, Size.M, "Katun", "Putih", "Bahan: Katun, Warna: Putih"));
        productManager.addProduct(new Clothing(6, "Knit Sweater", 180000, Size.L, "Wol", "Merah", "Bahan: Wol, Warna: Merah"));
        productManager.addProduct(new Clothing(7, "Gamis", 250000, Size.XL, "Sutra", "Hitam", "Bahan: Sutra, Warna: Hitam"));
        productManager.addProduct(new Clothing(8, "Celana Jeans", 200000, Size.S, "Denim", "Biru", "Bahan: Denim, Warna: Biru"));
        productManager.addProduct(new Clothing(9, "Rok Span", 150000, Size.M, "Polyester", "Abu-abu", "Bahan: Polyester, Warna: Abu-abu"));


        // Set model dan isi data dulu
        model = (DefaultTableModel) tableProduk.getModel();
        model.setRowCount(0); // kosongkan isi tabel dulu
        List<Product> listProduk = productManager.getAllProducts();
        for (Product p : listProduk) {
            model.addRow(new Object[]{p.getId(), p.getName(), p.getPrice(), p.getCategory(), p.getProductInfo()});
        }


        // Tampilkan garis
        tableProduk.setShowGrid(true);
        tableProduk.setGridColor(Color.BLACK);

        // Atur lebar kolom setelah data ditampilkan
        TableColumnModel columnModel = tableProduk.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(20); // Nama Produk
        columnModel.getColumn(1).setPreferredWidth(80); // Harga
        columnModel.getColumn(2).setPreferredWidth(50); // Kategori
        columnModel.getColumn(3).setPreferredWidth(50);
        columnModel.getColumn(3).setPreferredWidth(100);// Detail
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleMenu = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnKeranjang = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProduk = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 223, 200));

        jPanel2.setBackground(new java.awt.Color(220, 198, 166));

        titleMenu.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        titleMenu.setForeground(new java.awt.Color(249, 238, 223));
        titleMenu.setText("MENU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleMenu)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(220, 198, 166));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        btnKeranjang.setBackground(new java.awt.Color(253, 245, 234));
        btnKeranjang.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnKeranjang.setForeground(new java.awt.Color(102, 51, 0));
        btnKeranjang.setText("LIHAT KERANJANG");
        btnKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeranjangActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(253, 245, 234));
        btnKembali.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(102, 51, 0));
        btnKembali.setText("BACK");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DAFTAR PRODUK YANG TERSEDIA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tableProduk.setAutoCreateRowSorter(true);
        tableProduk.setBackground(new java.awt.Color(252, 244, 234));
        tableProduk.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        tableProduk.setForeground(new java.awt.Color(102, 51, 0));
        tableProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Laptop ASUS", "15000000", "Electronics", "Brand: Asus, Berat: 1.5 kg"},
                { new Integer(2), "HP Samsung", "6000000", "Electronics", "Brand: Samsung, Berat: 0.2 kg"},
                { new Integer(3), "TV LG", "1500000", "Electronics", "Brand: LF, Berat: 2.00 kg"},
                { new Integer(4), "Kipas Angin", "250000", "Electronics", "Brand: Maspion, Berat: 2.00 kg"},
                { new Integer(5), "Baju Polos", "120000", "Clothing", "Ukuran: M, Bahan: Katun"},
                { new Integer(6), "Knit Sweater", "180000", "Clothing", "Ukuran: L, Bahan: Wol, Warna: Merah"},
                { new Integer(7), "Gamis", "250000", "Clothing", "Ukuran: XL, Bahan: Sutra, Warna: Hitam"},
                { new Integer(8), "Celana Jeans", "200000", "Clothing", "Ukuran: S, Bahan: Denim, Warna: Biru"},
                { new Integer(9), "Rok Span", "150000", "Clothing", "Ukuran: M, Bahan: Polyester, Warna: Abu-abu"}
            },
            new String [] {
                "ID", "Nama Produk", "Harga (Rp)", " Kategori", "Detail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProduk.setColumnSelectionAllowed(true);
        tableProduk.setGridColor(new java.awt.Color(219, 197, 166));
        tableProduk.setSelectionBackground(new java.awt.Color(237, 222, 201));
        tableProduk.setSelectionForeground(new java.awt.Color(102, 51, 0));
        tableProduk.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableProduk.setShowGrid(true);
        jScrollPane2.setViewportView(tableProduk);
        tableProduk.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jScrollPane1.setViewportView(jScrollPane2);

        btnTambah.setBackground(new java.awt.Color(253, 245, 234));
        btnTambah.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(102, 51, 0));
        btnTambah.setText("TAMBAH KE KERANJANG");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeranjang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeranjangActionPerformed
        // TODO add your handling code here:
        new FormKeranjang(this.cart).setVisible(true); // kirim objek cart
        this.dispose();
        
    }//GEN-LAST:event_btnKeranjangActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new FormBeranda(cart).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tableProduk.getSelectedRow();
        if (selectedRow != -1) {
            try {
                int idProduk = Integer.parseInt(model.getValueAt(selectedRow, 0).toString()); // kolom ke-0 adalah ID
                Product p = productManager.findProductById(idProduk); // cari berdasarkan ID
                cart.addProduct(p); // tambahkan ke keranjang
                JOptionPane.showMessageDialog(this, "Produk \"" + p.getName() + "\" ditambahkan ke keranjang!");
            } catch (ProductNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Produk tidak ditemukan.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShoppingCart cart = new ShoppingCart();
                new FormMenu(cart).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKeranjang;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableProduk;
    private javax.swing.JLabel titleMenu;
    // End of variables declaration//GEN-END:variables
}
